HOPPER_LEFT_CAN_ID = 16
HOPPER_RIGHT_CAN_ID = 17


INDEXER_BOTTOM_CAN_ID = 18
INDEXER_TOP_CAN_ID = 19

# Shooter sensors and actuators
TURRET_CAN_ID = 13
HOOD_CAN_ID = 14
FLYWHEEL_MOTOR_CAN_ID = 15
TURRET_ENCODER_CAN_ID = 16
HOOD_ENCODER_CAN_ID = 17

# Shooter gear ratios
TURRET_ENCODER_GEAR_RATIO = 10
HOOD_SENSOR_TO_MECHANISM_GEAR_RATIO = 19
HOOD_ROTOR_TO_SENSOR_GEAR_RATIO = 8

# Shooter limits
FLYWHEEL_MAX_RPM = 1
SHOOTER_TURRET_ROTATION_SPEED = 0.12
HOOD_MIN_TARGET_ANGLE = 0.01  # rotations of the hood
HOOD_MAX_TARGET_ANGLE = 0.08  # rotations of the hood

DEADBAND = 0.15**2
