package frc.framework.systems;

import frc.framework.execution.ExecutionManager;
import frc.framework.execution.SystemCachableResult;

/**
 * Provides tools for systems to handle inputs and outputs
 */
public class SystemUpdateHelper {
	private final ExecutionManager executionManager;
	private final SystemInformation systemInformation;
	private final System system;
	private final SystemCachableResult cachableResult;
	
	/**
	 * Construct an update helper
	 *
	 * @param system            The system that is recieving and giving data
	 * @param systemInformation The information generated by the system during its configuration step
	 * @param executionManager  A reference to the current execution manager
	 * @param result            A cachable result to write output data to
	 */
	public SystemUpdateHelper(
		System system, SystemInformation systemInformation, ExecutionManager executionManager, SystemCachableResult result
	) {
		this.system = system;
		this.systemInformation = systemInformation;
		this.executionManager = executionManager;
		this.cachableResult = result;
	}
	
	/**
	 * Get the evaluation of a given value
	 *
	 * @param identifier The identifier of the value one is attempting to access
	 * @param <T>        The type of the value
	 *
	 * @return The current value associated with the identifier
	 */
	@SuppressWarnings(
		"unchecked"
	)
	public <T> T getValue(ValueIdentifier<T> identifier) {
		if (!systemInformation.getInputIds().contains(identifier.getId())) {
			throw new RuntimeException(
				"The system " + system.getId() + " tried to get the value of " + identifier
					.getId() + ", but it never specified ahead of time that it needs it, thus, we cannot be sure that the value has been set."
			);
		}
		
		return (T) cachableResult.get(executionManager, identifier.getId());
	}
	
	/**
	 * Output to a given value identifier
	 *
	 * @param identifier The identifier of the value this system is outputting to
	 * @param value      The value to be associated with the identifier
	 * @param <T>        The type of the value
	 */
	public <T> void setValue(ValueIdentifier<T> identifier, T value) {
		setValue(identifier, value, Priority.Default);
	}
	
	/**
	 * Output to a given value identifier
	 *
	 * @param identifier The identifier of the value this system is outputting to
	 * @param value      The value to be associated with the identifier
	 * @param priority   The priority of the value, higher {@link Priority#value} beats lower
	 * @param <T>        The type of the value
	 */
	public <T> void setValue(ValueIdentifier<T> identifier, T value, Priority priority) {
		if (!systemInformation.getOutputIds().contains(identifier.getId())) {
			throw new RuntimeException(
				"The system " + system.getId() + " tried to set the value of " + identifier
					.getId() + ", but it never specified ahead of time that it sets it, this is throwing an error as it could cause unintended logic bugs."
			);
		}
		
		cachableResult.set(identifier.getId(), value, priority.value);
	}
}
