# Hopper motor CAN IDs.
HOPPER_LEFT_MOTOR_CAN_ID = 55
HOPPER_RIGHT_MOTOR_CAN_ID = 59

# Indexer motor CAN IDs.
INDEXER_BACK_MOTOR_CAN_ID = 18
INDEXER_FRONT_MOTOR_CAN_ID = 19

# Flywheel CAN IDs.
FLYWHEEL_MOTOR_CAN_ID = 15
FLYWHEEL_ENCODER_CAN_ID = 60

# Turret CAN IDs.
TURRET_MOTOR_CAN_ID = 13
TURRET_ENCODER_CAN_ID = 16

TURRET_SENSOR_TO_MECHANISM_GEAR_RATIO = 10
TURRET_ROTOR_TO_SENSOR_GEAR_RATIO = 4.167

# Flywheel speed on robot enable.
FLYWHEEL_ENABLE_RPS = 1.0

# Flywheel gains.
FLYWHEEL_K_S = 0.2
FLYWHEEL_K_V = 0.13
FLYWHEEL_K_A = 0.0
FLYWHEEL_K_P = 0.25
FLYWHEEL_K_I = 0.0
FLYWHEEL_K_D = 0.0

# Hopper left motor gains.
HOPPER_LEFT_K_S = 0.5
HOPPER_LEFT_K_V = 0.123
HOPPER_LEFT_K_A = 0.0
HOPPER_LEFT_K_P = 0.5
HOPPER_LEFT_K_I = 0.0
HOPPER_LEFT_K_D = 0.0

# Hopper right motor gains.
HOPPER_RIGHT_K_S = 0.2
HOPPER_RIGHT_K_V = 0.123
HOPPER_RIGHT_K_A = 0.0
HOPPER_RIGHT_K_P = 0.5
HOPPER_RIGHT_K_I = 0.0
HOPPER_RIGHT_K_D = 0.0

# Default speed (in rotations per second) for hopper motors.
HOPPER_MOTORS_RPS_DEFAULT = 30.0

# Indexer back motor gains.
INDEXER_BACK_K_S = 0.4
INDEXER_BACK_K_V = 0.12
INDEXER_BACK_K_A = 0.0
INDEXER_BACK_K_P = 0.25
INDEXER_BACK_K_I = 0.0
INDEXER_BACK_K_D = 0.0

# Indexer front motor gains.
INDEXER_FRONT_K_S = 0.35
INDEXER_FRONT_K_V = 0.105
INDEXER_FRONT_K_A = 0.0
INDEXER_FRONT_K_P = 0.2
INDEXER_FRONT_K_I = 0.0
INDEXER_FRONT_K_D = 0.0

# Default speed (in rotations per second) for indexer motors.
INDEXER_MOTORS_RPS_DEFAULT = 20.0

# Hood CAN IDs.
HOOD_MOTOR_CAN_ID = 14
HOOD_ENCODER_CAN_ID = 17

# Hood gear ratios.
HOOD_SENSOR_TO_MECHANISM_GEAR_RATIO = 19
HOOD_ROTOR_TO_SENSOR_GEAR_RATIO = 8

# Hood range, in degrees.
HOOD_MIN_ANGLE_DEGREES = 3.6
HOOD_MAX_ANGLE_DEGREES = 28.8

# Hood gains.
HOOD_K_S = 0.0
HOOD_K_V = 0.0
HOOD_K_A = 0.0
HOOD_K_P = 330
HOOD_K_I = 0.0
HOOD_K_D = 0.1
HOOD_K_G = 0.0

# Turret PID gains.
TURRET_K_P = 70
TURRET_K_I = 0
TURRET_K_D = 0.1

TURRET_VEL_K_P = 1
TURRET_VEL_K_I = 0
TURRET_VEL_K_D = 0
TURRET_VEL_K_S = 0.24
TURRET_VEL_K_V = 1.5
TURRET_VEL_K_A = 0

# Hood Motion Magic gains.
HOOD_MM_CRUISE_VELOCITY = 10.0
HOOD_MM_ACCELERATION = 5.0
HOOD_MM_JERK = 100.0

# Turret Motion Magic gains
TURRET_MM_CRUISE_VELOCITY = 10.0
TURRET_MM_ACCELERATION = 7.0
TURRET_MM_JERK = 75.0