# Hopper motor CAN IDs.
HOPPER_LEFT_MOTOR_CAN_ID = 55
HOPPER_RIGHT_MOTOR_CAN_ID = 59

# Indexer motor CAN IDs.
INDEXER_BOTTOM_MOTOR_CAN_ID = 18
INDEXER_TOP_MOTOR_CAN_ID = 19

# Flywheel CAN IDs.
FLYWHEEL_MOTOR_CAN_ID = 15
FLYWHEEL_ENCODER_CAN_ID = 60

# Turret CAN IDs.
TURRET_MOTOR_CAN_ID = 13
TURRET_ENCODER_CAN_ID = 16

TURRET_SENSOR_TO_MECHANISM_GEAR_RATIO = 10  
TURRET_ROTOR_TO_SENSOR_GEAR_RATIO = 4.167

# Flywheel speed on robot enable.
FLYWHEEL_ENABLE_RPS = 1.0

# Flywheel gains.
FLYWHEEL_K_S = 0.2
FLYWHEEL_K_V = 0.13
FLYWHEEL_K_A = 0.0
FLYWHEEL_K_P = 0.25
FLYWHEEL_K_I = 0.0
FLYWHEEL_K_D = 0.0

# Hood CAN IDs.
HOOD_MOTOR_CAN_ID = 14
HOOD_ENCODER_CAN_ID = 17

# Hood gear ratios.
HOOD_SENSOR_TO_MECHANISM_GEAR_RATIO = 19
HOOD_ROTOR_TO_SENSOR_GEAR_RATIO = 8

# Turret PID gains.
TURRET_K_P = 70
TURRET_K_I = 0
TURRET_K_D = 0.1
